- hosts: personal-website

  tasks:
    - name: Clean up
      file:
        path: site
        state: absent
      become: yes

    - git:
        repo: https://github.com/NuclearOreo/ussamaazam.me.git
        dest: site
        version: production

    - name: Copy Important Files
      command: bash -c "cp -r domain_cert nginx.conf Dockerfile .env.production.local site"

    - name: Stop a container
      docker_container:
        name: site
        state: absent
      become: yes

    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
      become: yes

    - name: Build images for site
      docker_image:
        build:
          path: site
        name: ussamaazam.me
      become: yes

    - name: Switch Directoy
      command: bash -c "cd site"
      become: yes

    - name: Docker Compose
      command: bash -c "docker-compose up -d"
      become: yes
