- hosts: personal-website

  tasks:
   - git:
        repo: "https://github.com/NuclearOreo/ussamaazam.me.git"
        dest: ~/site
        version: production
  
   - name: Copy Important Files
     command: bash -c "cp -r domain_cert nginx.conf Dockerfile site"