- hosts: personal-website

  tasks:
    - name: Clean up
      file:
        path: site
        state: absent
      become: yes
      become_user: ussamaazam

    - git:
        repo: https://github.com/NuclearOreo/ussamaazam.me.git
        dest: site
        version: production

    - name: Copy Important Files
      command: bash -c "cp -r domain_cert nginx.conf Dockerfile .env.production.local site"

    - name: Stop a container
      docker_container:
        name: site
        state: absent
      become: yes
      become_user: ussamaazam

    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
      become: yes
      become_user: ussamaazam

    - name: Build images for site
      docker_image:
        build:
          path: site
        name: ussamaazamme_site
      become: yes
      become_user: ussamaazam

    - name: Start Container
      command: bash -c "docker run -it -p 80:80 -p 443:443 -d --name site --rm ussamaazamme_site"
      become: yes
      become_user: ussamaazam
