version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app/
      - git:/app/.git
      - node_modules:/app/node_modules
      - husky:/app/.husky/_
    ports:
      - 3000:3000

volumes:
  node_modules:
  husky:
  git:
