version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./:/app/
    environment:
      - REACT_APP_UNSPLASH=${UNSPLASH_CLIENT_ID}
    ports:
      - 3000:3000
    stdin_open: true
    tty: true