version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./.git:/app/.git
      - ./.eslintrc.js:/app/.eslintrc.js
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: sh -c "npm run prepare && npm start"