version: '3.9'
services:
  app:
    build: 
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
      - .husky:/app/.husky
    environment:
      - REACT_APP_UNSPLASH=${REACT_APP_UNSPLASH}
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  node_modules:
  .husky:
