version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: npm start