name: Website CI

on:
  push:
    branches: [deployment]

  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: site
      PROJECT_ID: website-353503

    steps:
      # - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY  }}'

      # - uses: google-github-actions/setup-gcloud@v0

      # - name: Use Node.js 16.15.1
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.15.1
      #     cache: 'npm'

      # - name: Install Packages
      #   run: npm install

      # - name: Run Linter
      #   run: npm run lint

      # - name: Run Unit Tests
      #   run: npm run test -- --coverage --watchAll=false

      # - name: Build Project
      #   run: npm run build

      # - name: Build Docker Image
      #   run: docker build -t $IMAGE_NAME:latest .

      # - name: Configure Docker Client
      #   run: gcloud auth configure-docker --quiet

      # - name: Push Docker Image to Container Registry (GCR)
      #   run: |-
      #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: compute SSH
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: website
          zone: us-east1-b
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          command: sudo su
