name: Website CI/CD

on:
  push:
    branches: [version-2]

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY  }}

      - uses: google-github-actions/setup-gcloud@v0

      - name: Use Node.js 18.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run coverage

      - name: Build Project
        run: npm run build

      - name: Build Docker Image
        run: docker build -t site:latest .

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          docker tag site:latest gcr.io/website-353503/site:latest
          docker push gcr.io/website-353503/site:latest

      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          image: 'gcr.io/website-353503/site:latest'
          region: 'us-east1'
          service: 'personal-site'
