name: Website CI

on:
  push:
    branches: [deployment]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
      - name: NPM Install
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test -- --coverage --watchAll=false
      - name: Build Site
        run: npm run build
