name: PR Checks

on:
  pull_request:
    branches: [version-2]

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3

      - name: Use Node.js 20.10.0
        with:
          node-version: 20.10.0
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run coverage
